Sprint4
ClevertecFrontendLab/ViachaslauVDmitruk pull request #2
Opened 2023-02-22 21:57 UTC by ViachaslauVDmitruk

Продолжил спринт 4 в предыдущей ветке... Задумался)

2023-02-22 22:03 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 16.
Количество непройденных тестов: 0.
***
**active-category-programming.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ViachaslauVDmitruk/1677103411/active-category-programming.png)
***
**clearing-search-input.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ViachaslauVDmitruk/1677103411/clearing-search-input.png)
***
**empty-category.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ViachaslauVDmitruk/1677103411/empty-category.png)
***
**find-books.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ViachaslauVDmitruk/1677103411/find-books.png)
***
**search-result-not-found.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ViachaslauVDmitruk/1677103411/search-result-not-found.png)

2023-02-23 06:16 UTC, SergeyGlazun approved these changes

2023-02-23 06:16 UTC, SergeyGlazun commented on src/components/card/card-list-view/card-list-view.tsx
>          <div className={styles.author}>
по самому спринту вроде норм, только нужно подправить верстку
![image](https://user-images.githubusercontent.com/70904466/220832808-04d78709-238f-4059-bbf9-735a1a8797e7.png)

2023-02-23 09:05 UTC, Ivan6813 requested changes

2023-02-23 09:05 UTC, Ivan6813 commented on src/components/books/books.module.scss
> +  grid-auto-rows: 1fr;
карточки надо прижать к левому краю

![msedge_aoGGuhqK2s](https://user-images.githubusercontent.com/79784960/220863321-12c28d9f-d0db-401b-8235-1a6c26335d55.png)

2023-02-23 09:17 UTC, ViachaslauVDmitruk commented on src/components/books/books.module.scss
> +  grid-auto-rows: 1fr;
Балин, мнения разошлись. Женя посоветовал по центру сделать)

2023-02-23 14:16 UTC, ViachaslauVDmitruk commented on src/components/navigate-list/navigate-list.tsx
> +                    <p data-test-id={activeBurger ? `burger-${path}` : `navigation-${path}`}>{name}</p>
у меня в одном месте находится этот компонент, поэтому я решил все сделать через переменную в сторе, которая отслеживает состояние навигационного меню

2023-02-23 14:49 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 87%.
Общее количество тестов: 16.
Количество непройденных тестов: 2.
***
**active-category-programming.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ViachaslauVDmitruk/1677163757/active-category-programming.png)
***
**bread crumbs -- desktop -- transfer from all books category to book page (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ViachaslauVDmitruk/1677163757/bread%20crumbs%20--%20desktop%20--%20transfer%20from%20all%20books%20category%20to%20book%20page%20(failed).png)
***
**bread crumbs -- desktop -- transfer from programming category to book page (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ViachaslauVDmitruk/1677163757/bread%20crumbs%20--%20desktop%20--%20transfer%20from%20programming%20category%20to%20book%20page%20(failed).png)
***
**clearing-search-input.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ViachaslauVDmitruk/1677163757/clearing-search-input.png)
***
**empty-category.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ViachaslauVDmitruk/1677163757/empty-category.png)
***
**find-books.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ViachaslauVDmitruk/1677163757/find-books.png)
***
**search-result-not-found.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ViachaslauVDmitruk/1677163757/search-result-not-found.png)

2023-02-23 15:08 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 81%.
Общее количество тестов: 16.
Количество непройденных тестов: 3.
***
**active-category-programming.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ViachaslauVDmitruk/1677164920/active-category-programming.png)
***
**bread crumbs -- desktop -- transfer from all books category to book page (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ViachaslauVDmitruk/1677164920/bread%20crumbs%20--%20desktop%20--%20transfer%20from%20all%20books%20category%20to%20book%20page%20(failed).png)
***
**bread crumbs -- tablet -- transfer from all books category to book page (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ViachaslauVDmitruk/1677164920/bread%20crumbs%20--%20tablet%20--%20transfer%20from%20all%20books%20category%20to%20book%20page%20(failed).png)
***
**bread crumbs -- tablet -- transfer from programming category to book page (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ViachaslauVDmitruk/1677164920/bread%20crumbs%20--%20tablet%20--%20transfer%20from%20programming%20category%20to%20book%20page%20(failed).png)
***
**clearing-search-input.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ViachaslauVDmitruk/1677164920/clearing-search-input.png)
***
**empty-category.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ViachaslauVDmitruk/1677164920/empty-category.png)
***
**find-books.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ViachaslauVDmitruk/1677164920/find-books.png)
***
**search-result-not-found.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ViachaslauVDmitruk/1677164920/search-result-not-found.png)

2023-02-23 18:34 UTC, Ivan6813 approved these changes

2023-02-23 19:21 UTC, merged